export const perks = [
  {
    id: 8100,
    key: "Domination",
    name: "Domination",
    types: [
      { id: 8112, key: "Electrocute", name: "Electrocute" },
      { id: 8128, key: "DarkHarvest", name: "Dark Harvest" },
      { id: 9923, key: "HailOfBlades", name: "Hail Of Blades" },
      { id: 8126, key: "CheapShot", name: "Cheap Shot" },
      { id: 8139, key: "TasteOfBlood", name: "Taste Of Blood" },
      { id: 8143, key: "SuddenImpact", name: "Sudden Impact" },
      { id: 8137, key: "SixthSense", name: "Sixth Sense" },
      { id: 8140, key: "GrislyMementos", name: "Grisly Mementos" },
      { id: 8141, key: "DeepWard", name: "Deep Ward" },
      { id: 8135, key: "TreauseHunter", name: "Treasure Hunter" },
      { id: 8105, key: "RelentlessHunter", name: "Relentless Hunter" },
      { id: 8106, key: "UltimateHunter", name: "Ultimate Hunter" },
    ],
  },
  {
    id: 8300,
    key: "Insipration",
    name: "Insipration",
    types: [
      { id: 8351, key: "GlacialAugment", name: "Glacial Augment" },
      { id: 8360, key: "UnsealedSpellbook", name: "Unsealed Spellbook" },
      { id: 8369, key: "FirstStrike", name: "First Strike" },
      { id: 8306, key: "HextechFlashtraption", name: "Hextech Flashtraption" },
      { id: 8304, key: "MagicalFootwear", name: "Magical Footwear" },
      { id: 8321, key: "CashBack", name: "Cash Back" },
      { id: 8313, key: "PerfectTiming", name: "Perfect Timing" },
      { id: 8352, key: "TimeWarpTonic", name: "Time Warp Tonic" },
      { id: 8345, key: "BiscuitDelivery", name: "Biscuit Delivery" },
      { id: 8347, key: "CosmicInsight", name: "Cosmic Insight" },
      { id: 8410, key: "ApproachVelocity", name: "Approach Velocity" },
      { id: 8316, key: "JackOfAllTrades", name: "Jack Of All Trades" },
    ],
  },
  {
    id: 8000,
    key: "Precision",
    name: "Precision",
    types: [
      { id: 8005, key: "PressTheAttack", name: "Press The Attack" },
      { id: 8008, key: "LethalTempo", name: "Lethal Tempo" },
      { id: 8021, key: "FleetFootwork", name: "Fleet Footwork" },
      { id: 8010, key: "Conqueror", name: "Conqueror" },
      { id: 9101, key: "AbsorbLife", name: "Absorb Life" },
      { id: 9111, key: "Triumph", name: "Triumph" },
      { id: 8009, key: "PresenceOfMind", name: "Presence Of Mind" },
      { id: 9104, key: "LegendAlacrity", name: "Legend: Alacrity" },
      { id: 9105, key: "LegendHaste", name: "Legend: Haste" },
      { id: 9103, key: "LegendBloodline", name: "Legend: Bloodline" },
      { id: 8014, key: "CoupDeGrace", name: "Coup De Grace" },
      { id: 8017, key: "CutDown", name: "Cut Down" },
      { id: 8299, key: "LastStand", name: "Last Stand" },
    ],
  },
  {
    id: 8400,
    key: "Resolve",
    name: "Resolve",
    types: [
      { id: 8437, key: "GraspOfTheUndying", name: "Grasp Of The Undying" },
      { id: 8439, key: "AfterShock", name: "After Shock" },
      { id: 8465, key: "Guardian", name: "Guardian" },
      { id: 8446, key: "Demolish", name: "Demolish" },
      { id: 8463, key: "FontOfLife", name: "Font Of Life" },
      { id: 8401, key: "ShieldBash", name: "Shield Bash" },
      { id: 8429, key: "Conditioning", name: "Conditioning" },
      { id: 8444, key: "SecondWind", name: "Second Wind" },
      { id: 8473, key: "BonePlating", name: "Bone Plating" },
      { id: 8451, key: "Overgrowth", name: "Overgrowth" },
      { id: 8453, key: "Revitalize", name: "Revitalize" },
      { id: 8242, key: "Unflinching", name: "Unflinching" },
    ],
  },
  {
    id: 8200,
    key: "Sorcery",
    name: "Sorcery",
    types: [
      { id: 8214, key: "SummonAery", name: "Summon Aery" },
      { id: 8229, key: "ArcaneComet", name: "Arcane Comet" },
      { id: 8230, key: "PhaseRush", name: "Phase Rush" },
      { id: 8224, key: "NullifyingOrb", name: "Nullifying Orb" },
      { id: 8226, key: "ManaflowBand", name: "Manaflow Band" },
      { id: 8275, key: "NimbusCloak", name: "Nimbus Cloak" },
      { id: 8210, key: "Transcendence", name: "Transcendence" },
      { id: 8234, key: "Celerity", name: "Celerity" },
      { id: 8233, key: "AbsoluteFocus", name: "Absolute Focus" },
      { id: 8237, key: "Scorch", name: "Scorch" },
      { id: 8232, key: "Waterwalking", name: "Waterwalking" },
      { id: 8236, key: "GatheringStorm", name: "Gathering Storm" },
    ],
  },
  {
    key: "Statmodifiers",
    name: "StatMods",
    types: [
      {
        id: 5008,
        name: "statmodsadaptiveforceicon",
        group: "Offense",
        icon: "statmodsadaptiveforceicon.png",
      },
      {
        id: 5005,
        name: "statmodsattackspeedicon",
        group: "Offense",
        icon: "statmodsattackspeedicon.png",
      },
      {
        id: 5007,
        name: "statmodscdrscalingicon",
        group: "Offense",
        icon: "statmodscdrscalingicon.png",
      },
      {
        id: 5008,
        name: "statmodsadaptiveforceicon",
        group: "Flex",
        icon: "statmodsadaptiveforceicon.png",
      },
      {
        id: 5010,
        name: "statmodsmovementspeedicon",
        group: "Flex",
        icon: "statmodsmovementspeedicon.png",
      },
      {
        id: 5001,
        name: "statmodshealthscalingicon",
        group: "Flex",
        icon: "statmodshealthscalingicon.png",
      },
      {
        id: 5011,
        name: "statmodshealthplusicon",
        group: "Defense",
        icon: "statmodshealthplusicon.png",
      },
      {
        id: 5013,
        name: "statmodstenacityicon",
        group: "Defense",
        icon: "statmodstenacityicon.png",
      },
      {
        id: 5001,
        name: "statmodshealthscalingicon",
        group: "Defense",
        icon: "statmodshealthscalingicon.png",
      },
    ],
  },
];
